// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoSort.Data;

#nullable disable

namespace PhotoSort.Migrations
{
    [DbContext(typeof(PhotoSortDbContext))]
    [Migration("20260718105832_RemoveVideoClipsAndPreviewStrips")]
    partial class RemoveVideoClipsAndPreviewStrips
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("PhotoSort.Models.Face", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BoundingBoxHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("BoundingBoxWidth")
                        .HasColumnType("REAL");

                    b.Property<double>("BoundingBoxX")
                        .HasColumnType("REAL");

                    b.Property<double>("BoundingBoxY")
                        .HasColumnType("REAL");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionModelVersion")
                        .HasColumnType("TEXT");

                    b.Property<double>("FaceAngle")
                        .HasColumnType("REAL");

                    b.Property<double>("FaceSize")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LandmarkX1")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkX2")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkX3")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkX4")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkX5")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkY1")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkY2")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkY3")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkY4")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkY5")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastRecognitionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RecognitionConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int>("RecognitionState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("DetectionModelVersion");

                    b.HasIndex("FaceSize");

                    b.HasIndex("IsIgnored");

                    b.HasIndex("LastRecognitionDate");

                    b.HasIndex("PhotoId");

                    b.HasIndex("RecognitionState");

                    b.ToTable("Faces");
                });

            modelBuilder.Entity("PhotoSort.Models.FaceEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmbeddingDimension")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNormalized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FaceId")
                        .IsUnique();

                    b.ToTable("FaceEmbeddings");
                });

            modelBuilder.Entity("PhotoSort.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScanDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedDate");

                    b.HasIndex("FolderPath")
                        .IsUnique();

                    b.HasIndex("LastScanDate");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("PhotoSort.Models.Memory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CoverPhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverThumbnailPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dismissed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastShownAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationSummary")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MemoryTypeEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeopleSummary")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("ShowCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SnoozedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorySummary")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateEnd");

                    b.HasIndex("DateStart");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("IsGenerated");

                    b.HasIndex("LastShownAt");

                    b.HasIndex("MemoryTypeEntityId");

                    b.HasIndex("Score");

                    b.HasIndex("IsArchived", "Dismissed");

                    b.ToTable("Memories", (string)null);
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryCacheEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryTypeKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("candidate");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Type");

                    b.ToTable("MemoryCache", (string)null);
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MemoryId");

                    b.ToTable("MemoryFeedback", (string)null);
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryGenerationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatesIn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatesOut")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryTypeKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("RunId", "Stage");

                    b.ToTable("MemoryGenerationHistory", (string)null);
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryItem", b =>
                {
                    b.Property<Guid>("MemoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("QualityScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("supporting");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemoryId", "PhotoId");

                    b.HasIndex("MemoryId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("MemoryId", "SortOrder");

                    b.ToTable("MemoryItems", (string)null);
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryPhoto", b =>
                {
                    b.Property<Guid>("MemoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Supporting");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemoryId", "PhotoId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("MemoryId", "SortOrder");

                    b.ToTable("MemoryPhotos", (string)null);
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcludedTypes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeScreenshots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDailyMemories")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinScore")
                        .HasColumnType("REAL");

                    b.Property<string>("MusicPreference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("none");

                    b.Property<string>("PreferredTypes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeekdayMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("balanced");

                    b.HasKey("Id");

                    b.ToTable("MemoryPreferences", (string)null);
                });

            modelBuilder.Entity("PhotoSort.Models.MemorySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastShownAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recurrence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MemorySchedules");
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryScore", b =>
                {
                    b.Property<Guid>("MemoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Brightness")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Composition")
                        .HasColumnType("REAL");

                    b.Property<double?>("EyeOpenness")
                        .HasColumnType("REAL");

                    b.Property<int?>("FaceCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Importance")
                        .HasColumnType("REAL");

                    b.Property<double?>("Noise")
                        .HasColumnType("REAL");

                    b.Property<double?>("QualityScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sharpness")
                        .HasColumnType("REAL");

                    b.Property<double?>("SmileScore")
                        .HasColumnType("REAL");

                    b.HasKey("MemoryId", "PhotoId");

                    b.HasIndex("CalculatedAt");

                    b.HasIndex("PhotoId");

                    b.ToTable("MemoryScores", (string)null);
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryStatistics", b =>
                {
                    b.Property<int>("MemoryTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalViewed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserDwellSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserFavoriteCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemoryTypeId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("MemoryStatistics", (string)null);
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultCoverStrategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("single");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("FamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPhotoCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinPhotoCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonalMonths")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tone")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("MemoryTypes", (string)null);
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryTypeFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("MemoryTypeFamilies", (string)null);
                });

            modelBuilder.Entity("PhotoSort.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FaceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastSeenDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThumbnailPhotoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("FaceCount");

                    b.HasIndex("LastSeenDate");

                    b.HasIndex("Name");

                    b.HasIndex("PhotoCount");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PhotoSort.Models.PersonFace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FaceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDate");

                    b.HasIndex("FaceId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonId", "FaceId")
                        .IsUnique();

                    b.ToTable("PersonFaces");
                });

            modelBuilder.Entity("PhotoSort.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraMake")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("ClassificationConfidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ClassificationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DuplicateGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HashCalculatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("MediaCategory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MetadataExtractedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Orientation")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("PerceptualHash")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PerceptualHashDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SimilarPhotoGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ThumbnailGeneratedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailMediumPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailSmallPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VideoThumbnailDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoThumbnailLargePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoThumbnailMediumPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("VideoThumbnailScore")
                        .HasColumnType("REAL");

                    b.Property<string>("VideoThumbnailSmallPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("VideoThumbnailTimestamp")
                        .HasColumnType("REAL");

                    b.Property<int>("VideoThumbnailVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("DateTaken");

                    b.HasIndex("DuplicateGroupId");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("FolderId");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("Latitude");

                    b.HasIndex("Longitude");

                    b.HasIndex("MediaCategory");

                    b.HasIndex("PerceptualHash");

                    b.HasIndex("SimilarPhotoGroupId");

                    b.HasIndex("State");

                    b.HasIndex("ThumbnailGeneratedDate");

                    b.HasIndex("FolderId", "State");

                    b.HasIndex("Latitude", "Longitude");

                    b.HasIndex("FolderId", "State", "ModifiedDateUtc");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("PhotoSort.Models.PhotoInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PhotoInteractions");
                });

            modelBuilder.Entity("PhotoSort.Models.PhotoPlace", b =>
                {
                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhotoId", "PlaceId");

                    b.HasIndex("PlaceId");

                    b.ToTable("PhotoPlaces");
                });

            modelBuilder.Entity("PhotoSort.Models.PhotoSignal", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Signals")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("PhotoId");

                    b.ToTable("PhotoSignals", (string)null);
                });

            modelBuilder.Entity("PhotoSort.Models.PhotoTag", b =>
                {
                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhotoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PhotoTags");
                });

            modelBuilder.Entity("PhotoSort.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Latitude");

                    b.HasIndex("Longitude");

                    b.HasIndex("Name");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("PhotoSort.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PhotoSort.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoverPhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverPhotoPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaceCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalDistanceKm")
                        .HasColumnType("REAL");

                    b.Property<int>("VideoCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("Name");

                    b.HasIndex("StartDate");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("PhotoSort.Models.TripPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateTaken");

                    b.HasIndex("PhotoId");

                    b.HasIndex("TripId");

                    b.HasIndex("TripId", "PhotoId")
                        .IsUnique();

                    b.ToTable("TripPhotos");
                });

            modelBuilder.Entity("PhotoSort.Models.TripPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstVisitDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastVisitDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripId");

                    b.HasIndex("TripId", "PlaceId")
                        .IsUnique();

                    b.ToTable("TripPlaces");
                });

            modelBuilder.Entity("PhotoSort.Models.UnknownFaceCluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("CentroidEmbedding")
                        .HasColumnType("BLOB");

                    b.Property<string>("ClusterLabel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNamed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UnknownFaceClusters");
                });

            modelBuilder.Entity("PhotoSort.Models.Face", b =>
                {
                    b.HasOne("PhotoSort.Models.Photo", "Photo")
                        .WithMany("Faces")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("PhotoSort.Models.FaceEmbedding", b =>
                {
                    b.HasOne("PhotoSort.Models.Face", "Face")
                        .WithOne("FaceEmbedding")
                        .HasForeignKey("PhotoSort.Models.FaceEmbedding", "FaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Face");
                });

            modelBuilder.Entity("PhotoSort.Models.Memory", b =>
                {
                    b.HasOne("PhotoSort.Models.MemoryTypeEntity", "MemoryTypeEntity")
                        .WithMany("Memories")
                        .HasForeignKey("MemoryTypeEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MemoryTypeEntity");
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryFeedback", b =>
                {
                    b.HasOne("PhotoSort.Models.Memory", "Memory")
                        .WithMany("FeedbackEntries")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryItem", b =>
                {
                    b.HasOne("PhotoSort.Models.Memory", "Memory")
                        .WithMany("Items")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryPhoto", b =>
                {
                    b.HasOne("PhotoSort.Models.Memory", "Memory")
                        .WithMany("Photos")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryScore", b =>
                {
                    b.HasOne("PhotoSort.Models.Memory", "Memory")
                        .WithMany("Scores")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryStatistics", b =>
                {
                    b.HasOne("PhotoSort.Models.MemoryTypeEntity", "MemoryType")
                        .WithMany()
                        .HasForeignKey("MemoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MemoryType");
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryTypeEntity", b =>
                {
                    b.HasOne("PhotoSort.Models.MemoryTypeFamily", "Family")
                        .WithMany("MemoryTypes")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("PhotoSort.Models.PersonFace", b =>
                {
                    b.HasOne("PhotoSort.Models.Face", "Face")
                        .WithMany("PersonFaces")
                        .HasForeignKey("FaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoSort.Models.Person", "Person")
                        .WithMany("PersonFaces")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Face");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PhotoSort.Models.Photo", b =>
                {
                    b.HasOne("PhotoSort.Models.Folder", "Folder")
                        .WithMany("Photos")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("PhotoSort.Models.PhotoPlace", b =>
                {
                    b.HasOne("PhotoSort.Models.Photo", "Photo")
                        .WithMany("PhotoPlaces")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoSort.Models.Place", "Place")
                        .WithMany("PhotoPlaces")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("PhotoSort.Models.PhotoTag", b =>
                {
                    b.HasOne("PhotoSort.Models.Photo", "Photo")
                        .WithMany("PhotoTags")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoSort.Models.Tag", "Tag")
                        .WithMany("PhotoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PhotoSort.Models.TripPhoto", b =>
                {
                    b.HasOne("PhotoSort.Models.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoSort.Models.Trip", "Trip")
                        .WithMany("TripPhotos")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("PhotoSort.Models.TripPlace", b =>
                {
                    b.HasOne("PhotoSort.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoSort.Models.Trip", "Trip")
                        .WithMany("TripPlaces")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("PhotoSort.Models.Face", b =>
                {
                    b.Navigation("FaceEmbedding");

                    b.Navigation("PersonFaces");
                });

            modelBuilder.Entity("PhotoSort.Models.Folder", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("PhotoSort.Models.Memory", b =>
                {
                    b.Navigation("FeedbackEntries");

                    b.Navigation("Items");

                    b.Navigation("Photos");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryTypeEntity", b =>
                {
                    b.Navigation("Memories");
                });

            modelBuilder.Entity("PhotoSort.Models.MemoryTypeFamily", b =>
                {
                    b.Navigation("MemoryTypes");
                });

            modelBuilder.Entity("PhotoSort.Models.Person", b =>
                {
                    b.Navigation("PersonFaces");
                });

            modelBuilder.Entity("PhotoSort.Models.Photo", b =>
                {
                    b.Navigation("Faces");

                    b.Navigation("PhotoPlaces");

                    b.Navigation("PhotoTags");
                });

            modelBuilder.Entity("PhotoSort.Models.Place", b =>
                {
                    b.Navigation("PhotoPlaces");
                });

            modelBuilder.Entity("PhotoSort.Models.Tag", b =>
                {
                    b.Navigation("PhotoTags");
                });

            modelBuilder.Entity("PhotoSort.Models.Trip", b =>
                {
                    b.Navigation("TripPhotos");

                    b.Navigation("TripPlaces");
                });
#pragma warning restore 612, 618
        }
    }
}
