// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoSort.Data;

#nullable disable

namespace PhotoSort.Migrations
{
    [DbContext(typeof(PhotoSortDbContext))]
    partial class PhotoSortDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("PhotoSort.Models.Face", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BoundingBoxHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("BoundingBoxWidth")
                        .HasColumnType("REAL");

                    b.Property<double>("BoundingBoxX")
                        .HasColumnType("REAL");

                    b.Property<double>("BoundingBoxY")
                        .HasColumnType("REAL");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionModelVersion")
                        .HasColumnType("TEXT");

                    b.Property<double>("FaceAngle")
                        .HasColumnType("REAL");

                    b.Property<double>("FaceSize")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LandmarkX1")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkX2")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkX3")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkX4")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkX5")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkY1")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkY2")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkY3")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkY4")
                        .HasColumnType("REAL");

                    b.Property<double>("LandmarkY5")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastRecognitionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RecognitionConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int>("RecognitionState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("DetectionModelVersion");

                    b.HasIndex("FaceSize");

                    b.HasIndex("IsIgnored");

                    b.HasIndex("LastRecognitionDate");

                    b.HasIndex("PhotoId");

                    b.HasIndex("RecognitionState");

                    b.ToTable("Faces");
                });

            modelBuilder.Entity("PhotoSort.Models.FaceEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmbeddingDimension")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNormalized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FaceId")
                        .IsUnique();

                    b.ToTable("FaceEmbeddings");
                });

            modelBuilder.Entity("PhotoSort.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScanDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedDate");

                    b.HasIndex("FolderPath")
                        .IsUnique();

                    b.HasIndex("LastScanDate");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("PhotoSort.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FaceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastSeenDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThumbnailPhotoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("FaceCount");

                    b.HasIndex("LastSeenDate");

                    b.HasIndex("Name");

                    b.HasIndex("PhotoCount");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PhotoSort.Models.PersonFace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FaceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDate");

                    b.HasIndex("FaceId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonId", "FaceId")
                        .IsUnique();

                    b.ToTable("PersonFaces");
                });

            modelBuilder.Entity("PhotoSort.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraMake")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("ClassificationConfidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ClassificationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DuplicateGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HashCalculatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("MediaCategory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MetadataExtractedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Orientation")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("PerceptualHash")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PerceptualHashDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewClipPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviewFrameCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreviewStripGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreviewStripVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SimilarPhotoGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ThumbnailGeneratedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailMediumPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailSmallPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VideoThumbnailDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoThumbnailLargePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoThumbnailMediumPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("VideoThumbnailScore")
                        .HasColumnType("REAL");

                    b.Property<string>("VideoThumbnailSmallPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("VideoThumbnailTimestamp")
                        .HasColumnType("REAL");

                    b.Property<int>("VideoThumbnailVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("DateTaken");

                    b.HasIndex("DuplicateGroupId");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("FolderId");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("Latitude");

                    b.HasIndex("Longitude");

                    b.HasIndex("MediaCategory");

                    b.HasIndex("PerceptualHash");

                    b.HasIndex("SimilarPhotoGroupId");

                    b.HasIndex("State");

                    b.HasIndex("ThumbnailGeneratedDate");

                    b.HasIndex("FolderId", "State");

                    b.HasIndex("Latitude", "Longitude");

                    b.HasIndex("FolderId", "State", "ModifiedDateUtc");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("PhotoSort.Models.PhotoPlace", b =>
                {
                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhotoId", "PlaceId");

                    b.HasIndex("PlaceId");

                    b.ToTable("PhotoPlaces");
                });

            modelBuilder.Entity("PhotoSort.Models.PhotoTag", b =>
                {
                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhotoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PhotoTags");
                });

            modelBuilder.Entity("PhotoSort.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Latitude");

                    b.HasIndex("Longitude");

                    b.HasIndex("Name");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("PhotoSort.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PhotoSort.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoverPhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverPhotoPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaceCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalDistanceKm")
                        .HasColumnType("REAL");

                    b.Property<int>("VideoCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("Name");

                    b.HasIndex("StartDate");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("PhotoSort.Models.TripPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateTaken");

                    b.HasIndex("PhotoId");

                    b.HasIndex("TripId");

                    b.HasIndex("TripId", "PhotoId")
                        .IsUnique();

                    b.ToTable("TripPhotos");
                });

            modelBuilder.Entity("PhotoSort.Models.TripPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstVisitDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastVisitDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripId");

                    b.HasIndex("TripId", "PlaceId")
                        .IsUnique();

                    b.ToTable("TripPlaces");
                });

            modelBuilder.Entity("PhotoSort.Models.Face", b =>
                {
                    b.HasOne("PhotoSort.Models.Photo", "Photo")
                        .WithMany("Faces")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("PhotoSort.Models.FaceEmbedding", b =>
                {
                    b.HasOne("PhotoSort.Models.Face", "Face")
                        .WithOne("FaceEmbedding")
                        .HasForeignKey("PhotoSort.Models.FaceEmbedding", "FaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Face");
                });

            modelBuilder.Entity("PhotoSort.Models.PersonFace", b =>
                {
                    b.HasOne("PhotoSort.Models.Face", "Face")
                        .WithMany("PersonFaces")
                        .HasForeignKey("FaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoSort.Models.Person", "Person")
                        .WithMany("PersonFaces")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Face");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PhotoSort.Models.Photo", b =>
                {
                    b.HasOne("PhotoSort.Models.Folder", "Folder")
                        .WithMany("Photos")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("PhotoSort.Models.PhotoPlace", b =>
                {
                    b.HasOne("PhotoSort.Models.Photo", "Photo")
                        .WithMany("PhotoPlaces")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoSort.Models.Place", "Place")
                        .WithMany("PhotoPlaces")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("PhotoSort.Models.PhotoTag", b =>
                {
                    b.HasOne("PhotoSort.Models.Photo", "Photo")
                        .WithMany("PhotoTags")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoSort.Models.Tag", "Tag")
                        .WithMany("PhotoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PhotoSort.Models.TripPhoto", b =>
                {
                    b.HasOne("PhotoSort.Models.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoSort.Models.Trip", "Trip")
                        .WithMany("TripPhotos")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("PhotoSort.Models.TripPlace", b =>
                {
                    b.HasOne("PhotoSort.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoSort.Models.Trip", "Trip")
                        .WithMany("TripPlaces")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("PhotoSort.Models.Face", b =>
                {
                    b.Navigation("FaceEmbedding");

                    b.Navigation("PersonFaces");
                });

            modelBuilder.Entity("PhotoSort.Models.Folder", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("PhotoSort.Models.Person", b =>
                {
                    b.Navigation("PersonFaces");
                });

            modelBuilder.Entity("PhotoSort.Models.Photo", b =>
                {
                    b.Navigation("Faces");

                    b.Navigation("PhotoPlaces");

                    b.Navigation("PhotoTags");
                });

            modelBuilder.Entity("PhotoSort.Models.Place", b =>
                {
                    b.Navigation("PhotoPlaces");
                });

            modelBuilder.Entity("PhotoSort.Models.Tag", b =>
                {
                    b.Navigation("PhotoTags");
                });

            modelBuilder.Entity("PhotoSort.Models.Trip", b =>
                {
                    b.Navigation("TripPhotos");

                    b.Navigation("TripPlaces");
                });
#pragma warning restore 612, 618
        }
    }
}
